str = "testing"
print(len(str))
print(str[0])
print(str.count('t'))
print(str.replace('ing','cases'))
print(str.index('s',0,4))
print(str.istitle())
print(str.isalnum())
print(str.capitalize())
print('This is {} class'.format('testing'))
print(str.split())
print(str.startswith('t'))
print(str.endswith('g'))
print(str.lower())
print(str.upper())